class_name Orders

var orders = {};

func moveIn(unitId,buildingId):
	if orders.has(unitId) == false:
		orders[unitId] = {};
	orders[unitId]["move_in"] = buildingId

func getSendFormat(factionId, password):
	var body = '';
	for unitId in orders:
		body = body + "\n";
		body = body + "unit %s" % unitId;
		for orderType in orders[unitId]:
			body = body + "\n";
			body = body + "move %s IN" % orders[unitId][orderType];
	return '
#atlantis %s "%s"

;Generated by super duper new client
%s

#end
' % [factionId, password, body];
